In [4]:
!pip install plotly

In [5]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [6]:
X, y = make_regression(
    n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50
)

In [7]:
df = pd.DataFrame({"feature1": X[:, 0], "feature2": X[:, 1], "target": y})

In [8]:
df.head()

feature1  feature2     target
0  0.831416 -0.551677 -92.030753
1 -0.464522 -1.809484  80.981817
2  0.671211 -1.240507  -9.651879
3 -0.716529 -0.509638 -86.139315
4  0.858437 -1.157410  50.050575

In [9]:
df.shape

(100, 3)

In [10]:
# plotly to 3d graph
px.scatter_3d(df, x="feature1", y="feature2", z="target")


ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'feature1=%{x}<br>feature2=%{y}<br>target=%{z}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'symbol': 'circle'},
              'mode': 'markers',
              'name': '',
              'scene': 'scene',
              'showlegend': False,
              'type': 'scatter3d',
              'x': {'bdata': ('HSNtXfWa6j9IIpKqubrdvxGXyv+Peu' ... '8tob7HP8lZAzU+++o/elvbr0fsxL8='),
                    'dtype': 'f8'},
              'y': {'bdata': ('Pl85k1an4b+IkAJ1pfP8vwsRzoYd2f' ... 'pm7Le2P184tXm0NMk/ey6qjukx4z8='),
                    'dtype': 'f8'},
              'z': {'bdata': ('C+aL2fcBV8DH4kUY1j5UQED1ABfDTS' ... '2aeWM/wKzM79hCYlRA8AvojgMeCkA='),
                    'dtype': 'f8'}}],
    'layout': {'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'scene': {'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
                         'xaxis': {'title': {'text': 'feature1'}},
                         'yaxis': {'title': {'text': 'feature2'}},
                         'zaxis': {'title': {'text': 'target'}}},
               'template': '...'}
})

In [11]:
# now from here goes the ml
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [12]:
# importing the model
from sklearn.linear_model import LinearRegression

In [13]:
model = LinearRegression()

In [14]:
model.fit(X_train, y_train)

LinearRegression()

In [15]:
y_prediction = model.predict(X_test)

In [16]:
print("MAE : ", mean_absolute_error(y_test, y_pred=y_prediction))
print("MSE : ", mean_squared_error(y_test, y_prediction))
print("R2 Score : ", r2_score(y_test, y_prediction))

MAE :  42.29333963120832
MSE :  2618.661658615879
R2 Score :  0.025101103623203613


## Building my Own Multiple Linear Regression model from scratch


### Mathematical formulation and coding for multiple lr

formula for predection : 

```y^ = beta0 + beta1 * x1 + beta2 * x2 + beta3 * x3```

here we are finding the values of `beta's` 

and to calculate the `beta` the mathematical formulation is:

``` beta = (X^T X) ^ -1 X^T Y```

X = Matrix (all the values of features columns)
Y = Y (what we have to predict)




In [17]:
# importing datasets from sklearn
from sklearn.datasets import load_diabetes

In [18]:
X, y = load_diabetes(return_X_y=True)

In [19]:
X.shape

(442, 10)

In [20]:
y.shape

(442,)

## using sklearn's linear regression 

In [ ]:
from sklearn.model_selection import train_test_split


SyntaxError: invalid syntax (3574218730.py, line 1)

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [23]:
print(X_train.shape)
print(X_test.shape)

(353, 10)
(89, 10)


In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
reg = LinearRegression()

In [26]:
reg.fit(X_train, y_train)

LinearRegression()

In [28]:
y_pred = reg.predict(X_test)


In [29]:
from sklearn.metrics import r2_score


In [30]:
r2_score(y_test, y_pred=y_pred)

0.439933866156897

In [31]:
reg.coef_  # values of betas

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [32]:
reg.intercept_  # this is the value of beta0

np.float64(151.88331005254167)

# Making my own LINEAR REGRESSION CLASS

In [52]:
class myLearningRegression:
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self, X_train, y_train):
        # adding that 1111 column to our x_train data set
        X_train = np.insert(X_train, 0, 1, axis=1)

        # calculate the coefs
        betas = np.linalg.inv(np.dot(X_train.T, X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]

    def predict(self, X_test):
        y_pred = np.dot(X_test, self.coef_) + self.intercept_
        return y_pred

In [53]:
lr = myLearningRegression()

In [54]:
lr.fit(X_train=X_train, y_train=y_train)

In [ ]:
y_pred = lr.predict(X_test)

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [56]:
r2_score(y_test, y_pred=y_pred)

0.439933866156897

In [57]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [60]:
lr.intercept_

np.float64(151.88331005254176)